ERROR | app | log_exception | Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw2\sourcecode\server.py", line 11, in index
    return render_template('index.html')
  File "C:\Python27\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw2\sourcecode\templates\base.html", line 30, in template
    {#('/games/', 'games', 'Games'),
TemplateSyntaxError: unexpected char u'#' at 800
ERROR | app | log_exception | Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1644, in handle_http_exception
    return handler(e)
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw2\sourcecode\server.py", line 17, in error_400
    return render_template('error.html', error=404, previous=previous), 404
  File "C:\Python27\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw2\sourcecode\templates\base.html", line 30, in template
    {#('/games/', 'games', 'Games'),
TemplateSyntaxError: unexpected char u'#' at 800
